# Generated by Django 3.2.16 on 2022-12-13 05:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('categorys', '0002_auto_20221213_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('deleted_at', models.DateField()),
                ('quantity', models.IntegerField(verbose_name='quantity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('deleted_at', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='description')),
                ('sku', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='product price')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorys.category')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.discount', verbose_name='')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productinventory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
